package com.sber.dlmm.admin.dto;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

/**
 * B-04 (Batch #5, Sprint 14) — weekly customer-success snapshot for PO.
 *
 * <p>Aggregated metrics that the PO currently pulls manually from the
 * admin UI каждую неделю. Auto-generated и dropped в the response;
 * the email/Slack delivery hook is a separate cron job (out of scope
 * for this MVP — endpoint только).
 *
 * <p>Период: last 7 calendar days от sysdate.
 *
 * @param weekEnding           last calendar day of the reported 7-day window
 * @param activeOrgs           organisations with ≥ 1 user login in the last 7 days (count)
 * @param activeUsers          users with ≥ 1 login in the last 7 days (count)
 * @param newUsers             users created in the last 7 days (count)
 * @param totalTransactions    transactions in the last 7 days (count)
 * @param swapCount            {@code SWAP} transactions in the last 7 days (count)
 * @param totalFeeRevenueRub   summed fee revenue for the window, in roubles (₽,
 *                             fee amounts × estimated RUB rate)
 * @param twoFaAdoptionPct     share of users with 2FA enabled, as a percentage (%)
 * @param kycVerifiedPct       share of users with KYC verified, as a percentage (%)
 * @param top5FeeYieldingOrgs  up to five organisations ranked by fee revenue
 * @param churnWarnings        organisations that traded recently but have since
 *                             gone quiet (churn-risk signals)
 */
public record CustomerSuccessWeekly(
        LocalDate weekEnding,
        int activeOrgs,                  // orgs с ≥ 1 user login за last 7d
        int activeUsers,                 // users с ≥ 1 login за last 7d
        int newUsers,                    // users created за last 7d
        int totalTransactions,           // txs за last 7d
        int swapCount,                   // SWAP txs за last 7d
        double totalFeeRevenueRub,       // sum of feeAmount * estimated RUB rate
        double twoFaAdoptionPct,         // % of users с 2FA enabled
        double kycVerifiedPct,           // % of users с kyc=VERIFIED
        List<TopOrg> top5FeeYieldingOrgs,
        List<ChurnWarning> churnWarnings  // orgs с tx до 14d, но no recent
) {
    /**
     * One entry in the weekly top-fee-yielding organisations leaderboard.
     *
     * @param orgId           identifier of the organisation
     * @param orgName         display name of the organisation
     * @param feeRevenueRub   fee revenue generated by the org in the window, in roubles (₽)
     * @param activeUserCount number of the org's users active in the window (count)
     */
    public record TopOrg(UUID orgId, String orgName, double feeRevenueRub, int activeUserCount) {}

    /**
     * A churn-risk signal: an organisation that transacted recently but has not
     * traded again within the watch window.
     *
     * @param orgId               identifier of the organisation
     * @param orgName             display name of the organisation
     * @param lastTransactionDate date of the org's most recent transaction (ISO-8601 date string)
     * @param daysSinceLast       days elapsed since that last transaction (count)
     */
    public record ChurnWarning(UUID orgId, String orgName, String lastTransactionDate, int daysSinceLast) {}
}
