package com.sber.dlmm.notification.controller;

import com.sber.dlmm.common.dto.PageResponse;
import com.sber.dlmm.notification.dto.NotificationResponse;
import com.sber.dlmm.notification.dto.UnreadCountResponse;
import com.sber.dlmm.notification.service.NotificationService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;
import java.util.UUID;

/**
 * REST controller exposing the user-facing notification API under {@code /api/v1/notifications}.
 *
 * <p>All endpoints operate on the <em>authenticated</em> user only: the user id is taken from
 * the {@link Authentication} (its name is the user's UUID, set by the shared JWT filter) and
 * never from a client parameter, so a caller can only ever see or mutate their own
 * notifications. The controller is a thin adapter — it parses the principal and delegates to
 * {@link NotificationService}. The constructor is generated by Lombok
 * ({@code @RequiredArgsConstructor}); the {@code @Tag} drives Swagger grouping.
 */
@RestController
@RequestMapping("/api/v1/notifications")
@RequiredArgsConstructor
@Tag(name = "Notifications", description = "User in-app notifications: list, unread count, and mark-as-read operations")
public class NotificationController {

    /** Service holding the notification read/mutate logic. */
    private final NotificationService notificationService;

    /**
     * Lists the authenticated user's notifications, newest first, with pagination.
     *
     * <p>When {@code unreadOnly} is true only unread notifications are returned (e.g. to drive an
     * "unread" filter); otherwise all notifications are returned. Maps to {@code GET /me}.
     *
     * @param authentication the security principal; its name is the caller's user UUID
     * @param unreadOnly     when {@code true}, return only unread notifications (default {@code false})
     * @param page           zero-based page index (default {@code 0})
     * @param size           page size, notifications per page (default {@code 20})
     * @return 200 with a {@link PageResponse} of {@link NotificationResponse} for the user
     */
    @GetMapping("/me")
    @Operation(summary = "List my notifications",
            description = "Returns the authenticated user's notifications, newest first, with pagination. "
                    + "Set unreadOnly=true to return only unread notifications.")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Page of notifications returned"),
            @ApiResponse(responseCode = "401", description = "Missing or invalid authentication token")
    })
    public ResponseEntity<PageResponse<NotificationResponse>> getMyNotifications(
            Authentication authentication,
            @Parameter(description = "When true, return only unread notifications")
            @RequestParam(defaultValue = "false") boolean unreadOnly,
            @Parameter(description = "Zero-based page index")
            @RequestParam(defaultValue = "0") int page,
            @Parameter(description = "Page size (number of notifications per page)")
            @RequestParam(defaultValue = "20") int size) {
        UUID userId = UUID.fromString(authentication.getName());
        PageResponse<NotificationResponse> response =
                notificationService.getUserNotifications(userId, unreadOnly, page, size);
        return ResponseEntity.ok(response);
    }

    /**
     * Marks one of the authenticated user's notifications as read.
     *
     * <p>No-op if the notification is already read; if no notification with that id belongs to
     * the user the service throws (surfaced as 404). Maps to {@code POST /{id}/read}.
     *
     * @param id             identifier of the notification to mark read (path variable)
     * @param authentication the security principal; its name is the caller's user UUID
     * @return 200 with an empty body on success
     */
    @PostMapping("/{id}/read")
    @Operation(summary = "Mark a notification as read",
            description = "Marks a single notification, owned by the authenticated user, as read. No-op if already read.")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Notification marked as read"),
            @ApiResponse(responseCode = "401", description = "Missing or invalid authentication token"),
            @ApiResponse(responseCode = "404", description = "Notification not found for this user")
    })
    public ResponseEntity<Void> markAsRead(
            @Parameter(description = "Identifier of the notification to mark as read")
            @PathVariable UUID id,
            Authentication authentication) {
        UUID userId = UUID.fromString(authentication.getName());
        notificationService.markAsRead(id, userId);
        return ResponseEntity.ok().build();
    }

    /**
     * Marks every unread notification of the authenticated user as read in one call.
     *
     * <p>Backs a "mark all read" action; delegates to a single bulk update. Maps to
     * {@code POST /read-all}.
     *
     * @param authentication the security principal; its name is the caller's user UUID
     * @return 200 with an empty body on success
     */
    @PostMapping("/read-all")
    @Operation(summary = "Mark all my notifications as read",
            description = "Marks every unread notification of the authenticated user as read in one operation.")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "All notifications marked as read"),
            @ApiResponse(responseCode = "401", description = "Missing or invalid authentication token")
    })
    public ResponseEntity<Void> markAllAsRead(Authentication authentication) {
        UUID userId = UUID.fromString(authentication.getName());
        notificationService.markAllAsRead(userId);
        return ResponseEntity.ok().build();
    }

    /**
     * Returns the count of unread notifications for the authenticated user.
     *
     * <p>Intended for the notification-bell badge counter. Maps to {@code GET /me/unread-count}.
     *
     * @param authentication the security principal; its name is the caller's user UUID
     * @return 200 with an {@link UnreadCountResponse} carrying the unread count
     */
    @GetMapping("/me/unread-count")
    @Operation(summary = "Count my unread notifications",
            description = "Returns the number of unread notifications for the authenticated user (e.g. for a badge counter).")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Unread notification count returned"),
            @ApiResponse(responseCode = "401", description = "Missing or invalid authentication token")
    })
    public ResponseEntity<UnreadCountResponse> getUnreadCount(Authentication authentication) {
        UUID userId = UUID.fromString(authentication.getName());
        long count = notificationService.getUnreadCount(userId);
        return ResponseEntity.ok(new UnreadCountResponse(count));
    }

    /**
     * Returns the authenticated user's unread notification counts grouped by category,
     * as a JSON object keyed by category name (e.g.
     * {@code {"MARGIN_WARNING": 3, "FEE_ACCRUED": 2}}). Categories with no unread
     * notifications are omitted. Backs a categorised bell badge.
     *
     * @param authentication the security principal; its name is the caller's user UUID
     * @return 200 with the per-category unread counts
     */
    @GetMapping("/me/unread-count-by-type")
    @Operation(summary = "Count my unread notifications grouped by category",
            description = "Returns the authenticated user's unread notification counts keyed by "
                    + "category name (e.g. for a categorised badge). Empty categories are omitted.")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Per-category unread counts returned"),
            @ApiResponse(responseCode = "401", description = "Missing or invalid authentication token")
    })
    public ResponseEntity<Map<String, Long>> getUnreadCountByType(Authentication authentication) {
        UUID userId = UUID.fromString(authentication.getName());
        return ResponseEntity.ok(notificationService.getUnreadCountByType(userId));
    }
}
