-- ============================================================================
-- 13-seed-sync-fee-display.sql  —  RETIRED (no-op)
--
-- Superseded by the Meteora per-bin fee model (single source of truth) and
-- 14-seed-bin-fee-growth.sql.
--
-- This script used to reconcile three independent fee sources (the stored
-- lp_positions.unclaimed_fee column, the live per-position fee-growth delta, and
-- the fee_accruals ledger) by syncing the display to the claimable amount and
-- advancing the single position-wide last_fee_growth snapshot to MAX(bin growth).
--
-- That whole class of drift is gone now: pool-engine's PER-BIN fee growth
-- (pool_bins.fee_growth vs position_bins.fee_growth_checkpoint) is the only fee
-- source. getUserPositions, the fee claim and the summary all compute owed from
-- it, and a claim advances each bin's checkpoint exactly — so display ≡ claimable
-- with no reconciliation needed. The seed state is set by 14-seed-bin-fee-growth.sql.
--
-- Kept as an intentional no-op so existing references / run-order don't break.
-- ============================================================================

SELECT 1;  -- no-op
