package com.sber.dlmm.notification.security;

import lombok.RequiredArgsConstructor;
import org.springframework.boot.actuate.autoconfigure.security.servlet.EndpointRequest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;
import com.sber.dlmm.common.security.JwtAuthenticationFilter;

/**
 * Spring Security configuration for the notification-service HTTP layer.
 *
 * <p>Establishes a stateless, JWT-authenticated REST surface: the shared
 * {@link JwtAuthenticationFilter} from {@code dlmm-common} validates the bearer token and
 * builds the {@code Authentication} whose name is the user id the controller relies on.
 * Swagger and actuator endpoints are left open; every {@code /api/v1/notifications/**} route
 * (and anything else) requires authentication. CSRF is disabled because the API is token-based
 * and never relies on cookies/sessions. The constructor is generated by Lombok
 * ({@code @RequiredArgsConstructor}).
 */
@Configuration
@EnableWebSecurity
@EnableMethodSecurity
@RequiredArgsConstructor
public class SecurityConfig {

    /** Shared JWT filter (from {@code dlmm-common}) inserted ahead of the username/password filter. */
    private final JwtAuthenticationFilter jwtAuthenticationFilter;

    /**
     * Builds the security filter chain governing all incoming HTTP requests.
     *
     * <p>Disables CSRF, forces stateless session management, permits Swagger and all actuator
     * endpoints (using {@code EndpointRequest} to dodge the Spring 6.2 MvcRequestMatcher
     * inference that would otherwise drop actuator paths), requires authentication for the
     * notification API and every other request, and registers the JWT filter before the
     * standard {@link UsernamePasswordAuthenticationFilter}.
     *
     * @param http the {@link HttpSecurity} builder to configure
     * @return the built {@link SecurityFilterChain}
     * @throws Exception if the security configuration cannot be assembled
     */
    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http
                .csrf(AbstractHttpConfigurer::disable)
                .sessionManagement(session -> session.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
                .authorizeHttpRequests(auth -> auth
                        .requestMatchers("/swagger-ui/**", "/v3/api-docs/**", "/swagger-ui.html").permitAll()
                        // EndpointRequest avoids the Spring 6.2 MvcRequestMatcher
                        // inference that silently drops actuator paths.
                        .requestMatchers(EndpointRequest.toAnyEndpoint()).permitAll()
                        .requestMatchers("/api/v1/notifications/**").authenticated()
                        .anyRequest().authenticated()
                )
                .addFilterBefore(jwtAuthenticationFilter, UsernamePasswordAuthenticationFilter.class);
        return http.build();
    }
}
