package com.sber.dlmm.notification.entity;

import com.sber.dlmm.common.enums.NotificationType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity for a single user notification, persisted in the {@code notifications} table.
 *
 * <p>This is the canonical record produced when a domain event is consumed from Kafka and
 * turned into something a user can see. The notification-service is the only writer of this
 * table. Accessors and the all-args/no-args constructors and builder are generated by Lombok
 * ({@code @Getter}/{@code @Setter}/{@code @NoArgsConstructor}/{@code @AllArgsConstructor}/
 * {@code @Builder}); the {@link #onCreate()} lifecycle hook is the only hand-written method.
 *
 * <p>Note the JPA property is {@code read} but the column is {@code is_read} (because a bare
 * {@code read} column name would clash with reserved words on some databases).
 */
@Entity
@Table(name = "notifications")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Notification {

    /** Surrogate primary key, generated as a random UUID by the JPA provider on insert. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owner of the notification; every query is scoped by this so users only see their own. */
    @Column(nullable = false)
    private UUID userId;

    /** Notification category, stored as its enum name (e.g. {@code SWAP_COMPLETED}, {@code MARGIN_CALL}). */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private NotificationType type;

    /** Short headline shown to the user; required. */
    @Column(nullable = false)
    private String title;

    /** Human-readable body (capped at 2000 chars to bound row size); required. */
    @Column(nullable = false, length = 2000)
    private String message;

    /** Original raw event JSON the notification was derived from; nullable, stored as TEXT. */
    @Column(columnDefinition = "TEXT")
    private String payload;

    /** Read flag; defaults to {@code false} (unread). Mapped to column {@code is_read}. */
    @Column(name = "is_read", nullable = false)
    @Builder.Default
    private boolean read = false;

    /** Creation timestamp; set on insert (see {@link #onCreate()}) if not supplied. */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /** Timestamp the notification was marked read, or {@code null} while still unread. */
    private LocalDateTime readAt;

    /**
     * JPA pre-persist callback that stamps {@link #createdAt} with the current time when the
     * caller did not set it explicitly.
     *
     * <p>Guards against persisting a row with a null creation time (the column is non-null)
     * while still honoring an explicitly provided value (e.g. for backfills/tests).
     */
    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}
