package com.sber.dlmm.common.audit;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Sprint 8 #AU-4 — admin audit log (audit C-6 critical).
 *
 * <p><b>Sprint 9-DS-r4 (P2-13)</b> — moved out of {@code dlmm-user-service}
 * into {@code dlmm-common.audit} so transaction-service + pool-engine
 * (and any future service with admin mutations) can wire the same
 * aspect/writer without copy-paste. All services share one Postgres
 * schema, so the {@code admin_audit_log} table is the single source
 * of truth — analysts query one place.
 *
 * <p>Append-only record of every admin mutation that runs through an
 * {@code @AdminAudit}-annotated method. Captured by {@link AdminAuditAspect}
 * via Spring AOP — no caller-side bookkeeping required.
 *
 * <p>Never updated, never deleted. Compliance replay relies on
 * immutability. JPA mapping omits @PreUpdate / setters for written-once
 * fields to make accidental mutation harder.
 */
@Entity
@Table(name = "admin_audit_log")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AdminAuditLog {

    /** Outcome of the audited call: {@code SUCCESS} or {@code FAILED}. */
    public enum Status { SUCCESS, FAILED }

    /** Surrogate primary key, generated by JPA on persist. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Sprint 13 G-28 / S13-02 — distinguishes ADMIN-side mutations
     * (KYC update, pool pause, OTC quote) from USER-side mutations
     * (swap, add/remove liquidity, fee claim). Defaults to
     * {@link ActorType#ADMIN} so call sites that don't specify behave
     * the same way they did pre-S13-02, and any pre-existing rows in
     * the DB stay valid (column has DEFAULT 'ADMIN').
     */
    @Column(name = "actor_type", nullable = false, length = 10)
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private ActorType actorType = ActorType.ADMIN;

    /**
     * UUID of the user who triggered the action — admin id for ADMIN-side
     * audits, end-user id for USER-side audits. Null only for reserved
     * system audits.
     */
    @Column(name = "actor_user_id")
    private UUID actorUserId;

    /**
     * "ROLE_ADMIN" / "ROLE_SUPER_ADMIN" / "ROLE_USER" — pulled from JWT
     * authorities at write time. Combined with {@link #actorType} this
     * captures both "what hat are they wearing" and "what permission did
     * the JWT carry" — useful for spotting privilege-escalation patterns.
     */
    @Column(name = "actor_role", length = 40)
    private String actorRole;

    /**
     * Action label from {@code @AdminAudit#action()}, e.g. "USER_BLOCK",
     * "USER_KYC_UPDATE", "POOL_PAUSE", "OTC_QUOTE". Stable identifier for
     * analyst queries.
     */
    @Column(nullable = false, length = 60)
    private String action;

    /** "USER" / "POOL" / "TOKEN" / "OTC" / "TX" — coarse-grained filter axis. */
    @Column(name = "target_type", length = 40)
    private String targetType;

    /** Stringified UUID, symbol, or composite ID of the target object. */
    @Column(name = "target_id", length = 120)
    private String targetId;

    /** Whether the audited call succeeded or threw — set by the aspect after the method runs. */
    @Column(nullable = false, length = 20)
    @Enumerated(EnumType.STRING)
    private Status status;

    /** Truncated exception message when {@link Status#FAILED}; null on SUCCESS. */
    @Column(name = "error_message", length = 500)
    private String errorMessage;

    /** Class.method — useful when same action label fires from multiple call sites. */
    @Column(name = "method_signature", length = 200)
    private String methodSignature;

    /** IPv4 / IPv6 — pulled from X-Forwarded-For if behind gateway, else RemoteAddr. */
    @Column(name = "ip_address", length = 45)
    private String ipAddress;

    /** Write timestamp. {@code updatable = false} reinforces the append-only contract. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * JPA lifecycle callback that stamps {@link #createdAt} with the current
     * time on first persist if the caller did not set it. Runs once per row
     * (insert only) — there is deliberately no {@code @PreUpdate} counterpart
     * because audit rows are never updated.
     */
    @PrePersist
    void onCreate() {
        if (createdAt == null) createdAt = LocalDateTime.now();
    }
}
